sonar.projectKey=DevTestOps
sonar.projectName=DevTestOps

# Dossiers à analyser
sonar.sources=src
sonar.tests=tests

# Exclure les dossiers inutiles
sonar.exclusions=**/node_modules/**,**/dist/**,**/.playwright/**,**/test-results/**

# TypeScript
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Encodage
sonar.sourceEncoding=UTF-8

# Serveur
sonar.host.url=http://localhost:9000